name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore "Sistema de Autenticação (Login + JWT).sln"

      - name: Build
        run: dotnet build "Sistema de Autenticação (Login + JWT).sln" --no-restore --configuration Release

      - name: Test with Coverage
        run: dotnet test "AuthApi.Tests/AuthApi.Tests.csproj" --configuration Release --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=./coverage/ /p:ExcludeByFile="**/obj/**"

      - name: Verify coverage report
        run: |
          ls -la ./AuthApi.Tests/coverage
          test -f ./AuthApi.Tests/coverage/coverage.cobertura.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./AuthApi.Tests/coverage/coverage.cobertura.xml
          slug: gabiRioRange/AuthService.API
          disable_search: true
          fail_ci_if_error: true
          verbose: true